my_string = input('Введите произвольный текст: ')
print('Количество символов в введённом тексте:', len(my_string))
print('Строка в вверхнем регистре:', my_string.upper())
print('Строка в нижнем регистре:', my_string.lower())
print('Строка с уддалёнными пробелами:', my_string.replace(' ', ''))
print('Первый символ строки:', my_string[0])
print('Последний символ строки:', my_string[-1])